### ISSUE TITLE
错误,LNK2001,无法解析的外部符号 "class onnx2trt_onnx

### ISSUE THREAD

**Issue by YQMCU** [xjsxujingsong/FairMOT_TensorRT#4]
你好：
       我在用vs2017+win10环境中编译遇到了onnx2trt链接问题。
       针对这个问题于是进行重新编译onnx-tensorrt，发现onnx似乎对windows平台不支持，
       请问你的onnx是用什么版本，是否针对windows平台作了改动？

       错误信息：
     
       严重性        代码        说明        项目        文件        行        禁止显示状态
      错误        LNK2001        无法解析的外部符号 "class onnx2trt_onnx::TensorShapeProtoDefaultTypeInternal 
      onnx2trt_onnx::_TensorShapeProto_default_instance_" (? 
      _TensorShapeProto_default_instance_@onnx2trt_onnx@@3VTensorShapeProtoDefaultTypeInternal@1@A)        TensorRT        
      D:\soft\develop\0602_mot\FairMOT_TensorRT\ModelImporter.obj        1

**Comment by xjsxujingsong** [comment]
你需要按照tensorRTIntegrate这个项目把DCN (centernet)跑起来，然后再用我这个工程。如果想简单一点，就打开我另一个工程不需要DCN的，不需要编译那么多库

**Comment by YQMCU** [comment]
> 你需要按照tensorRTIntegrate这个项目把DCN (centernet)跑起来，然后再用我这个工程。如果想简单一点，就打开我另一个工程不需要DCN的，不需要编译那么多库

感谢，按照你的指导，已经顺利的把tensorRTIntegrate项目跑起来的，但是仍然无法跑起来当前这个项目。

错误信息： 无法解析的外部符号 “public __cdecl onnx2trt_onnx::ModelProto::ModelProto(void*)” 等

那么请教大佬， FairMOT_TensorRT 项目和 tersorRTIntegrate 项目，**它们之间是什么关系 ？ 如何能够关联起来呢**？

我看到你工程属性中有 study\onnx\build\install\lib\debug\*.lib , **这个 onnx 文件夹是从哪里获取的**。

![err](https://user-images.githubusercontent.com/20901897/122023659-56666000-cdfa-11eb-8248-6da4cbd757b1.png)

**Comment by xjsxujingsong** [comment]
我的工程的src目录基本就是tersorRTIntegrate这个项目。如果你那边已经跑通了，那你只要关心mot目录就可以了，你可可以把mot目录拷贝到你已经编译好的tersorRTIntegrate下。因为Fairmot和centernet都用到了DCN。理论上你只要把调用模型的地方改成mot就好了

**Comment by YQMCU** [comment]
> 我的工程的src目录基本就是tersorRTIntegrate这个项目。如果你那边已经跑通了，那你只要关心mot目录就可以了，你可可以把mot目录拷贝到你已经编译好的tersorRTIntegrate下。因为Fairmot和centernet都用到了DCN。理论上你只要把调用模型的地方改成mot就好了

你的意思是把 FairMot项目中的 mot 目录拷贝到 tensorRTIntegrate 项目中，那么，main.cpp 主程序是否需要怎么修改？
如果可以能不能留个联系方式，以便于直接请教你。感谢。

**Comment by xjsxujingsong** [comment]
你把tensorRTIntegrate的main拿掉就好了，我的mot目录里面有main函数

**Comment by YQMCU** [comment]
现在已经跑通了,但是我在用导出的模型进行运行时又出现了以下问题，
[libprotobuf FATAL d:\soft\develop\0602_mot\tensorrtintegrate-master\lean\protobuf3.11.4\include\google\protobuf\repeated_field.h:1537] CHECK failed: (index) < (current_size_):
CHECK failed: (index) < (current_size_):
网上说是protobuf的问题，但是我不确定这是模型导出的问题，还是其他的问题。
如果是我模型导出的问题，能否提供下您代码中的fairmot_dla34_switch_id_dim_1088x608模型。
非常感谢耐心回复！

**Comment by YQMCU** [comment]
> 现在已经跑通了,但是我在用导出的模型进行运行时又出现了以下问题，
> [libprotobuf FATAL d:\soft\develop\0602_mot\tensorrtintegrate-master\lean\protobuf3.11.4\include\google\protobuf\repeated_field.h:1537] CHECK failed: (index) < (current_size_):
> CHECK failed: (index) < (current_size_):
> 网上说是protobuf的问题，但是我不确定这是模型导出的问题，还是其他的问题。
> 如果是我模型导出的问题，能否提供下您代码中的fairmot_dla34_switch_id_dim_1088x608模型。
> 非常感谢耐心回复！

**Comment by xjsxujingsong** [comment]
pls check the latest commit.

**Comment by YQMCU** [comment]
你好, 目前问题比较清晰了，我在用你提供的onnx模型和我自己导出的模型在生成engin时都会出现以下问题：
         **repeated_field.h:1537] CHECK failed: (index) < (current_size_):CHECK failed: (index) < (current_size_)。**
但是用tensorRTIntegrate项目中提供的dladcnv2.onnx模型是完全可以生成engin的。
还有我发现你这边提供的compile engine的方法接口和tensorRTIntegrate中compile engine的方法参数数量对应不上。发现你重新实现了trt_builder。
         我的问题是tensorRTIntegrate项目中除了trt_builder需要改动，剩下的改动多吗？如果多的话，我直接使用你的代码。如果方便的话，能否直接提供下生成的engin文件。以及没有dcn的onnx、engin文件。不胜感谢！

**Comment by YQMCU** [comment]
还有我发现你这边提供的compile engine的方法接口和tensorRTIntegrate中compile engine的方法参数数量对应不上。不知道这块是不是改动了。

**Comment by xjsxujingsong** [comment]
可能那个项目后面更新了。我建议你在已经成功编译他的项目的基础上，只要把我这里mot的内容拷贝过去就好了。fairmot的onnx文件按照我修改的部分，你自己导出onnx就好了，没有dcn的fairmot在我的另一个项目里面，我也上传了onnx文件。engine文件给你没有用的，这个文件和机器相关，两台windows机器都不通用。

**Comment by YQMCU** [comment]
> 可能那个项目后面更新了。我建议你在已经成功编译他的项目的基础上，只要把我这里mot的内容拷贝过去就好了。fairmot的onnx文件按照我修改的部分，你自己导出onnx就好了，

就是按照这个流程操作的，但是onnx文件无法转化成engin文件。转化的trt_builder区别还是很大的。

**Comment by xjsxujingsong** [comment]
你自己用centernet生成的onnx可以转化吗？如果可以，那你自己转fairmot的onnx应该也没问题，就改了个输出内容而已

**Comment by YQMCU** [comment]
还是不行，两个项目代码相差实在太大。能否提供下 study\onnx\这个依赖文件，或者说明下这个依赖文件是怎么编译的呢？
不胜感激！

**Comment by xjsxujingsong** [comment]
这个很久了，当时这就是按照那个项目一步一步自己编译的。你先把我的项目放下，既然他的项目通过了，你可以自己把fairmot的onnx放进去了，只要在模型输出的时候多加上一个reid特征就好了。

Centernet 和fairmot的模型方面就是后者多了一个输出而已。

另外你必须要dcn吗？建议你直接用我的另一个不要dcn的项目，很容易就搭建起来了

**Comment by YQMCU** [comment]
问题就在Centernet 和fairmot的模型方面就是后者多了一个输出这里。
这个多出来的输出多出了expand算子，但是在tensorRTIntegrate项目中没有expand算子。
所以tensorRTIntegrate项目无法解析fairmot的模型。
![1222222](https://user-images.githubusercontent.com/20901897/122847712-cd3fb380-d33a-11eb-8492-10fbb2fb45a6.png)

**Comment by YQMCU** [comment]
我把你在pose_dla_dcn中的代码，屏蔽了下面两行，可以进行运行。
   id_feature = F.normalize(id_feature, dim=1)
   id_feature = id_feature.permute(0, 2, 3, 1).contiguous() 
normalize我可以理解，为什么要对 id_feature进行permute??

**Comment by xjsxujingsong** [comment]
我这边转换onnx没什么问题，或者你试试onnx simplify. 纬度变换是因为C++后处理处理起来更方便。你可以自己写一下后处理就明白了

**Comment by starry226** [comment]
你好，能直接提供一下你那边onnx_onnx2trt_onnx-ml.pb.cpp文件吗？模型转换的确有问题。

**Comment by xjsxujingsong** [comment]
这个文件是按照那个工程自动生成的，我的版本给你了也没啥用吧

**Comment by starry226** [comment]
你好，相同环境配置，应该可以直接使用的。麻烦提交分享一下。

> 这个文件是按照那个工程自动生成的，我的版本给你了也没啥用吧

**Comment by xjsxujingsong** [comment]
链接：https://pan.baidu.com/s/1zitOeHaXsQP1u4JdYX6Z9w 
提取码：p5qw

**Comment by starry226** [comment]
这个代码应该是基础版本，不是包含了你添加的reid输出的版本。
运行的时候会报如下错误：
NVInfer ERROR: (Unnamed Layer* 232) [Slice]: the start input tensors must be specified if any dynamic tensor is specified.

可能麻烦你找一下代码对应的版本？文件名应该是 onnx_onnx2trt_onnx-ml.pb.cc，onnx-operators_onnx2trt_onnx-ml.pb.cc

 > 链接：https://pan.baidu.com/s/1zitOeHaXsQP1u4JdYX6Z9w
 > 提取码：p5qw

**Comment by xjsxujingsong** [comment]
我电脑里面就这一个版本，对的，这个没有reid。
你需要把tensorRTIntegrate这个项目跑起来，它是针对centernet的。而Fairmot就是在centernet基础上在输出部分多了个reid分支而已。所以tensorRTIntegrate跑起来之后，意味着DCN搞定了，你就可以自己把tensorRTIntegrate里面模型输出部分改一下就好。我这个项目里面 基本就是tensorRTIntegrate那边拿过来的，就是修改了main.cpp， 然后加了mot目录才是tracking。

**Comment by starry226** [comment]
好的，谢谢
