### ISSUE TITLE
fairmot模型转换

### ISSUE THREAD

**Issue by Crystalxd** [xjsxujingsong/FairMOT_TensorRT#5]
作者您好！当我在转换使用dladcn_export_onnx.py脚本进行模型转换时，遇到了这个问题，请问该如何解决？加载的模型是fairmot_dla34.pth，pose_dla_dcn.py已修改。
dl@localhost:~/data/liuxx/FairMOT/src$ python dladcn_export_onnx.py 
Traceback (most recent call last):
  File "dladcn_export_onnx.py", line 21, in <module>
    model.load_state_dict(change)
  File "/home/dl/anaconda3/envs/arcface/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DLASeg:
        Unexpected key(s) in state_dict: "id.0.weight", "id.0.bias", "id.2.weight", "id.2.bias". 
        size mismatch for hm.2.weight: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 256, 1, 1]).
        size mismatch for hm.2.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for wh.2.weight: copying a param with shape torch.Size([4, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 256, 1, 1]).
        size mismatch for wh.2.bias: copying a param with shape torch.Size([4]) from checkpoint, the shape in current model is torch.Size([2]).

其中dladcn_export_onnx.py代码如下：

# 请下载官方的代码，然后执行这个就可以生成了
import _init_paths
import numpy as np
import torch
import torch.onnx.utils as onnx
import models.networks.pose_dla_dcn as net
from collections import OrderedDict
import cv2

model = net.get_pose_net(num_layers=34, heads={'hm': 80, 'wh': 2, 'reg': 2})

# https://github.com/xingyizhou/CenterNet/blob/master/readme/MODEL_ZOO.md 这里下载的
# 如果下载不了，可以尝试我提供的连接：http://zifuture.com:1000/fs/public_models/ctdet_coco_dla_2x.pth
checkpoint = torch.load(r"fairmot_dla34.pth", map_location="cpu")
checkpoint = checkpoint["state_dict"]
change = OrderedDict()
for key, op in checkpoint.items():
    change[key.replace("module.", "", 1)] = op

model.load_state_dict(change)
model.eval()
model.cuda()

input = torch.zeros((1, 3, 32, 32)).cuda()

# 有个已经导出好的模型：http://zifuture.com:1000/fs/public_models/dladcnv2.onnx
onnx.export(model, (input), "dladcnv2.onnx", output_names=["hm", "wh", "reg", "hm_pool"], verbose=True)

**Comment by xjsxujingsong** [comment]
You need to change the code to fit Fairmot that only consider people detection, not coco 80 classes.
Try this:

model = net.get_pose_net(num_layers=34, heads={'hm': 1, 'wh': 4, 'reg': 2, 'id':128})
onnx.export(model, (input), "your_model.onnx", output_names=["hm", "wh", "reg", "hm_pool", "id"], verbose=True)

**Comment by Crystalxd** [comment]
@xjsxujingsong  感谢作者！已完成导出。

**Comment by Crystalxd** [comment]
@xjsxujingsong 感谢作者！已完成导出。

**Comment by Crystalxd** [comment]
I modified 'dladcn_export_onnx.py' (which is in FairMOT/src directory)as follows:
```
# 请下载官方的代码，然后执行这个就可以生成了
import _init_paths
import numpy as np
import torch
import torch.onnx.utils as onnx
import models.networks.pose_dla_dcn as net

from models.model import create_model, load_model
from lib.opts import opts
from collections import OrderedDict
import cv2

opt = opts().init()
# model = net.get_pose_net(num_layers=34, heads={'hm': 1, 'wh': 4, 'reg': 2})
# model = create_model('dla_34', opt.heads, 256)
model = create_model(opt.arch, opt.heads, opt.head_conv)
# model = load_model(model, model_path)
# https://github.com/xingyizhou/CenterNet/blob/master/readme/MODEL_ZOO.md 这里下载的
# 如果下载不了，可以尝试我提供的连接：http://zifuture.com:1000/fs/public_models/ctdet_coco_dla_2x.pth
checkpoint = torch.load("../models/fairmot_dla34.pth", map_location="cpu")
checkpoint = checkpoint["state_dict"]
change = OrderedDict()
for key, op in checkpoint.items():
    change[key.replace("module.", "", 1)] = op

model.load_state_dict(change)
model.eval()
model.cuda()

input = torch.zeros((1, 3, 32, 32)).cuda()    # the size could be reseted

# 有个已经导出好的模型：http://zifuture.com:1000/fs/public_models/dladcnv2.onnx
onnx.export(model, (input), "fairmot_dla34.onnx", output_names=["hm", "wh", "reg", "hm_pool"], verbose=True)
```
 ,
I come across an error that shows  "ONNX export failed: Couldn't export Python operator _DCNv2" likes #2  when running this script, then I solved it by replacing dcn_v2.py in tensorRTIntegrate repo to FairMOT/src/lib/models/networks/DCNv2.

**Comment by xjsxujingsong** [comment]
Goodluck. 
BTW, I strongly suggest you try https://github.com/xjsxujingsong/FairMOT_TensorRT_C  which does not reply on DCN and it is faster.

**Comment by Crystalxd** [comment]
Much appreciated!

**Comment by PeppermintSummer** [comment]
`input = torch.zeros((1, 3, 32, 32)).cuda()`   input shape should be changed (1088,608)?

**Comment by Crystalxd** [comment]
@PeppermintSummer Yes. This is standard input in python env, I think it could be scaled down, maybe accelerate the speed in inference, but I have not dug into this code to figure out whether it is feasible to.

**Comment by xjsxujingsong** [comment]
Yes, you should. But it also works for 32x32. You can try by yourself. Btw, you need to export id frature as well.

**Comment by opentld** [comment]
我的转换脚本：

# 请下载官方的代码，然后执行这个就可以生成了
import _init_paths
import numpy as np
import torch
import torch.onnx.utils as onnx
import models.networks.pose_dla_dcn as net
from collections import OrderedDict
import cv2

model = net.get_pose_net(num_layers=34, heads={'hm': 1, 'wh': 4, 'reg': 2, 'id':128})

# https://github.com/xingyizhou/CenterNet/blob/master/readme/MODEL_ZOO.md 这里下载的
# 如果下载不了，可以尝试我提供的连接：http://zifuture.com:1000/fs/public_models/ctdet_coco_dla_2x.pth
checkpoint = torch.load(r"../models/ctdet_coco_dla_2x.pth", map_location="cpu")
checkpoint = checkpoint["state_dict"]
change = OrderedDict()
for key, op in checkpoint.items():
    change[key.replace("module.", "", 1)] = op

model.load_state_dict(change)
model.eval()
model.cuda()

input = torch.zeros((1, 3, 32, 32)).cuda()

# 有个已经导出好的模型：http://zifuture.com:1000/fs/public_models/dladcnv2.onnx
onnx.export(model, (input), "dladcnv2.onnx", output_names=["hm", "wh", "reg", "hm_pool", "id"], verbose=True)

fairmot_dla34.pth  模型下载路径：
https://drive.google.com/file/d/1iqRQjsG9BawIl8SlFomMg5iwkb6nqSpi/view?usp=sharing

运行结果：
(dlenv) D:\SourceCodes\Tracking\FairMOT-master\src>python dladcn_export_onnx.py mot
Traceback (most recent call last):
  File "dladcn_export_onnx.py", line 20, in <module>
    model.load_state_dict(change)
  File "D:\DevelopTools\anaconda3\envs\dlenv\lib\site-packages\torch\nn\modules\module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DLASeg:
        Missing key(s) in state_dict: "id.0.weight", "id.0.bias", "id.2.weight", "id.2.bias".
        Unexpected key(s) in state_dict: "base.fc.weight", "base.fc.bias".
        size mismatch for hm.2.weight: copying a param with shape torch.Size([80, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 256, 1, 1]).
        size mismatch for hm.2.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([1]).
        size mismatch for wh.2.weight: copying a param with shape torch.Size([2, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([4, 256, 1, 1]).
        size mismatch for wh.2.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([4]).

按照您说的修改了dladcn_export_onnx.py，可是依然有错啊？
或者您直接给个转换好的onnx文件？

@xjsxujingsong

**Comment by xjsxujingsong** [comment]
checkpoint = torch.load(r"../models/ctdet_coco_dla_2x.pth", map_location="cpu")

你这里怎么放进去的是centernet的模型？应该换成fairmot啊。我更新了代码，转换的python代码以及onnx都已经上传了。

**Comment by opentld** [comment]
> checkpoint = torch.load(r"../models/ctdet_coco_dla_2x.pth", map_location="cpu")
> 
> 你这里怎么放进去的是centernet的模型？应该换成fairmot啊。我更新了代码，转换的python代码以及onnx都已经上传了。

抱歉，手误，敲错了。。。
多谢！@xjsxujingsong

**Comment by wc1229** [comment]
`import cv2
import numpy as np
import torch
import torch.onnx.utils as onnx
import lib.models.networks.pose_dla_dcn as net
from lib.models.model import create_model, load_model
from lib.opts import opts
from collections import OrderedDict

model = net.get_pose_net(num_layers=34, heads={'hm': 1, 'wh': 4, 'reg': 2, 'id':128})
opt = opts().init()
#model = create_model(opt.arch, opt.heads, opt.head_conv)

checkpoint = torch.load(r"/home/lpj/wc/FairMOT-master/exp/mot/mot17_dla34/model_last.pth", map_location="cpu")
#/home/lpj/wc/FairMOT-master/models/fairmot_dla34.pth
#/home/lpj/wc/FairMOT-master/exp/mot/mot17_dla34/model_last.pth
checkpoint = checkpoint["state_dict"]
change = OrderedDict()
for key, op in checkpoint.items():
    change[key.replace("module.", "", 1)] = op

model.load_state_dict(change)
model.eval()
model.cuda()

input = torch.zeros((1, 3, 608, 1088)).cuda()
[hm, wh, reg, hm_pool, id_feature] = model(input)
onnx.export(model, (input), "fairmot_dla34_1088x608.onnx", output_names=["hm", "wh", "reg", "hm_pool", "id"], verbose=True)`
出现该错误：
Traceback (most recent call last):
  File "dla34_onnx.py", line 7, in <module>
    from lib.opts import opt
ImportError: cannot import name 'opt'
请问是什么问题呢

**Comment by wc1229** [comment]
`Traceback (most recent call last):
  File "dla34_onnx.py", line 7, in <module>
    from lib.opts import opt
ImportError: cannot import name 'opt'
`
出现该错误：
raceback (most recent call last):
  File "dla34_onnx.py", line 25, in <module>
    [hm, wh, reg, hm_pool, id_feature] = model(input)
ValueError: not enough values to unpack (expected 5, got 1)
请问是什么问题呢

**Comment by wc1229** [comment]
`import cv2
import numpy as np
import torch
import torch.onnx.utils as onnx
import lib.models.networks.pose_dla_dcn as net
from lib.models.model import create_model, load_model
from lib.opts import opts
from collections import OrderedDict

model = net.get_pose_net(num_layers=34, heads={'hm': 1, 'wh': 4, 'reg': 2, 'id':128})
opt = opts().init()
#model = create_model(opt.arch, opt.heads, opt.head_conv)

checkpoint = torch.load(r"/home/lpj/wc/FairMOT-master/exp/mot/mot17_dla34/model_last.pth", map_location="cpu")
#/home/lpj/wc/FairMOT-master/models/fairmot_dla34.pth
#/home/lpj/wc/FairMOT-master/exp/mot/mot17_dla34/model_last.pth
checkpoint = checkpoint["state_dict"]
change = OrderedDict()
for key, op in checkpoint.items():
    change[key.replace("module.", "", 1)] = op

model.load_state_dict(change)
model.eval()
model.cuda()

input = torch.zeros((1, 3, 608, 1088)).cuda()
[hm, wh, reg, hm_pool, id_feature] = model(input)
onnx.export(model, (input), "fairmot_dla34_1088x608.onnx", output_names=["hm", "wh", "reg", "hm_pool", "id"], verbose=True)`
出现该错误：
raceback (most recent call last):
File "dla34_onnx.py", line 25, in
[hm, wh, reg, hm_pool, id_feature] = model(input)
ValueError: not enough values to unpack (expected 5, got 1)
请问是什么问题呢

**Comment by xjsxujingsong** [comment]
需要修改模型定义，forward函数，具体见readme文件
