### ISSUE TITLE
pt to onnx

### ISSUE THREAD

**Issue by shuowoshishui** [xjsxujingsong/FairMOT_TensorRT#8]
hello, thx for your works, but there are some questions in my project, convert the onnx model failed, have you ever meet this problems?
what should i do? thank you!

**Comment by xjsxujingsong** [comment]
Pls check the issues before.
________________________________
From: shuowoshishui ***@***.***>
Sent: Friday, November 19, 2021 5:14:29 PM
To: xjsxujingsong/FairMOT_TensorRT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [xjsxujingsong/FairMOT_TensorRT] pt to onnx (Issue #8)


hello, thx for your works, but there are some questions in my project, convert the onnx model failed, have you ever meet this problems?
what should i do? thank you!

**Comment by shuowoshishui** [comment]
ok,i i can run this code , but the model cannot work well, cannot detect the person.

**Comment by xjsxujingsong** [comment]
​        detconfig.​fairmot​.​ltrb​ = ​true​; 
How.about change it to false.

It should work. I use this onnx to generate tensorrt.engine before uploading to github.

**Comment by shuowoshishui** [comment]
I can generate the engine model, and i set detconfig.​fairmot​.​ltrb​ = false​; but the output is also wrong.
